Update changelog after upgrade to faraday 2
ashkan18/graphlient pull request #97
Opened 2022-10-06 08:26 UTC by kirillkaiumov

Relates to https://github.com/ashkan18/graphlient/pull/95

2022-10-07 15:31 UTC, dblock requested changes
Fix danger please?

2022-10-07 15:31 UTC, dblock commented on CHANGELOG.md
> +### 0.7.0 (Next)
The version in https://github.com/ashkan18/graphlient/blob/master/lib/graphlient/version.rb should be incremented with this.

2022-10-07 15:31 UTC, dblock commented on CHANGELOG.md
> -* Your contribution here.
Put this back :)

2022-10-11 13:22 UTC, ashkan18 commented
thanks @kirillkaiumov , I resolved the conflicts which addresses @dblock 's concern as well. I'll merge once green.

2022-10-11 13:24 UTC, merged